[
   {
      "slider_img_url":"https://raw.githubusercontent.com/TaiyabMachhaliy/JSON/main/MiniWall/miniwall_slider_images/miniwall%20amoled.png",
      "url":null
   },
   {
     "slider_img_url":"https://raw.githubusercontent.com/TaiyabMachhaliy/JSON/main/MiniWall/miniwall_slider_images/miniwall%20amoled.png",
      "url":null
   },
   {
     "slider_img_url":"https://raw.githubusercontent.com/TaiyabMachhaliy/JSON/main/MiniWall/miniwall_slider_images/miniwall%20amoled.png",
      "url":null
   },
   {
     "slider_img_url":"https://raw.githubusercontent.com/TaiyabMachhaliy/JSON/main/MiniWall/miniwall_slider_images/miniwall%20amoled.png",
      "url":null
   },
   {
     "slider_img_url":"https://raw.githubusercontent.com/TaiyabMachhaliy/JSON/main/MiniWall/miniwall_slider_images/miniwall%20amoled.png",
      "url":null
   }
]
