[
   {
      "slider_img_url":"https://i.imgur.com/5gnVE7u.jpg",
      "url":"https://amzn.to/3PWKiTG"
   },
   {
     "slider_img_url":"https://i.imgur.com/Rcs5LKb.jpg",
      "url":"https://amzn.to/3BnM64c"
   },
   {
     "slider_img_url":"https://i.imgur.com/YnoY70c.jpg",
      "url":"https://amzn.to/3PLzjwH"
   },
 {
     "slider_img_url":"https://i.imgur.com/usdBx6O.jpg",
      "url":"https://amzn.to/3OH9DA7"
   }
]
